Add install script for backlight

diff --git a/link/bin/backlight b/link/bin/backlight
--- a/link/bin/backlight
+++ b/link/bin/backlight
@@ -112,6 +112,21 @@ __main() {
   if [ $# -eq 0 ] ; then
     __cmd_get
   else
+    if [ $1 = "install" ] ; then
+      if [ ! -d /etc/udev/rules.d -o ! -w /etc/udev/rules.d ] ; then
+        echo "Cannot write to /etc/udev/rules.d; run with sudo much?"
+        exit 1
+      else
+        cat <<EOF > /etc/udev/rules.d/backlight.rules
+ACTION=="add", SUBSYSTEM=="backlight", RUN+="/bin/chgrp video /sys/class/backlight/%k/brightness"
+ACTION=="add", SUBSYSTEM=="backlight", RUN+="/bin/chmod g+w /sys/class/backlight/%k/brightness"
+EOF
+        echo "Udev rules installed for video group; attemping to chgrp/mod existing backlights"
+        /bin/chgrp video /sys/class/backlight/*/brightness
+        /bin/chmod g+w /sys/class/backlight/*/brightness
+        exit 0
+      fi
+    fi
     __cmd_set "$@"
   fi
 }
